name: Build Tweak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: $HOME/theos

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang make perl git wget unzip ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS

      - name: Download iOS SDK
        run: |
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          wget https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* .
          rm -rf master.zip sdks-master

      - name: Build package
        run: |
          export PATH="/usr/bin:$PATH"
          make package FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tweak
          path: packages/*.deb
